### ISSUE TITLE
MockAlertVerifier instantiation causes failure in presenting another viewcontroller in main app

### ISSUE THREAD

**Issue by pragatisamant** [jonreid/MockUIAlertController#8]
I instantiate mockalertverifier in setup of xctestcase. Then I invoke Login which is expected to present an navigation controller.The code executes fine but nothing is presented.This makes it difficult to use alertverifier in setup method.

**Comment by jonreid** [comment]
@pragatisamant Can you share a code sample?

**Comment by jonreid** [comment]
Please reopen if you can reproduce the problem in an example.
