### ISSUE TITLE
Adding to swift project

### ISSUE THREAD

**Issue by malcolmkmd** [jonreid/MockUIAlertController#9]
I have installed the pod file to my test target, adding a bridging header and set its path in the build settings but still get unresolved identifier when trying to instantiate a QCOMockAlertVerifier. Please if possible provide step by step instructions of how to implement with swift. Thanks.

**Comment by jonreid** [comment]
Did you figure it out?

**Comment by malcolmkmd** [comment]
Hi  Jon, 

Yes I did after installing the pod there was no need for the bridging header. I've been using your pod successfully. Thanks for you response. 

Kind regards,
Malcolm Kumwenda

**Comment by jonreid** [comment]
👍
